#!/usr/bin/env python3
"""
Export enterprise leave-behind artifacts as Markdown and HTML.

Generates three artifact types in reports/artifacts/:
  - scorecard.{md,html}        — eval score summary across all 5 caps
  - compliance_report.{md,html} — EU AI Act obligation assessment (cap-05)
  - mrp_report.{md,html}       — Merge Readiness Pack (cap-02)

Usage:
    python scripts/export_artifacts.py
    python scripts/export_artifacts.py --output-dir reports/artifacts/
    python scripts/export_artifacts.py --formats md         # Markdown only
    python scripts/export_artifacts.py --formats html       # HTML only
    python scripts/export_artifacts.py --formats md html    # Both (default)
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = ROOT / "scripts" / "templates" / "artifacts"
DEFAULT_OUTPUT_DIR = ROOT / "reports" / "artifacts"
REPORTS_DIR = ROOT / "reports"

CAP_NAMES = {
    "cap-01": "Decision Intelligence",
    "cap-02": "Agentic Engineering (SASE)",
    "cap-03": "Agentic Commerce",
    "cap-04": "Autonomous Operations",
    "cap-05": "Compliance Intelligence",
}

ENFORCEMENT_DATE = "August 2, 2026"
DAYS_REMAINING = 46


def _run_subprocess(cmd: list[str], desc: str) -> subprocess.CompletedProcess:
    env = {**os.environ, "LLM_MODE": os.environ.get("LLM_MODE", "mock"), "PYTHONPATH": str(ROOT)}
    result = subprocess.run(cmd, cwd=ROOT, env=env, capture_output=True, text=True, timeout=120)
    if result.returncode != 0:
        print(f"WARNING: {desc} failed (exit {result.returncode})", file=sys.stderr)
        if result.stderr:
            print(result.stderr[:300], file=sys.stderr)
    return result


def load_or_generate_cap05(output_dir: Path) -> dict:
    """Load existing cap-05 report or generate it by running the demo."""
    json_path = output_dir / "eu_ai_act_demo.json"
    if json_path.exists():
        return json.loads(json_path.read_text(encoding="utf-8"))

    _run_subprocess(
        [sys.executable, str(ROOT / "cap-05-compliance-intelligence" / "demo.py"),
         "--query", "What are the Annex III high-risk AI system obligations?",
         "--output", str(json_path)],
        "cap-05 demo",
    )

    if json_path.exists():
        return json.loads(json_path.read_text(encoding="utf-8"))
    return {"cap": "cap-05", "status": "missing", "score": 0.0, "metrics": {}, "answers": [], "blocking_failures": []}


def load_or_generate_cap02(output_dir: Path) -> dict:
    """Load existing cap-02 MRP report or generate it by running the demo."""
    json_path = output_dir / "cap02_mrp.json"
    if json_path.exists():
        return json.loads(json_path.read_text(encoding="utf-8"))

    _run_subprocess(
        [sys.executable, str(ROOT / "cap-02-agentic-engineering" / "demo.py"),
         "--output", str(json_path)],
        "cap-02 demo",
    )

    if json_path.exists():
        return json.loads(json_path.read_text(encoding="utf-8"))
    return {"cap": "cap-02", "status": "missing", "score": 0.0, "metrics": {}, "blocking_failures": [], "merge_readiness_pack": {}}


def load_eval_reports() -> dict[str, dict]:
    """Load eval reports from reports/ directory."""
    reports = {}
    for cap in CAP_NAMES:
        json_path = REPORTS_DIR / f"{cap}.json"
        if json_path.exists():
            try:
                reports[cap] = json.loads(json_path.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                reports[cap] = {}
        else:
            reports[cap] = {}
    return reports


def _badge(status: str, score: float) -> str:
    if status == "pass" and score >= 0.85:
        return "pass"
    if not status or status in ("missing", "not_found", "no_eval_suite"):
        return "gray"
    if status in ("fail", "error"):
        return "fail"
    return "warn"


def render_scorecard_md(eval_reports: dict, generated_at: str, llm_mode: str) -> str:
    lines = [
        "# AI Capability Eval Scorecard",
        "",
        f"> Generated: {generated_at} | Mode: {llm_mode} | ai-native-capabilities",
        "",
        "| Capability | Status | Score | Blocking failures | Time |",
        "|---|---|---|---|---|",
    ]
    for cap, name in CAP_NAMES.items():
        r = eval_reports.get(cap, {})
        status = r.get("status", "—")
        score = r.get("score", 0.0)
        score_str = f"{score:.2f}" if score else "—"
        blocking = r.get("blocking_failures", [])
        blocking_str = ", ".join(blocking) if blocking else "none"
        elapsed = r.get("elapsed_s", None)
        time_str = f"{elapsed}s" if elapsed else "—"
        lines.append(f"| **{cap}** {name} | {status} | {score_str} | {blocking_str} | {time_str} |")
    lines += [
        "",
        "---",
        "*Generated by ai-native-capabilities · [DEPLOYMENT.md](DEPLOYMENT.md)*",
    ]
    return "\n".join(lines)


def render_compliance_md(cap05_data: dict, generated_at: str, llm_mode: str) -> str:
    answers = cap05_data.get("answers", [])
    metrics = cap05_data.get("metrics", {})
    audit_events = metrics.get("audit_events", cap05_data.get("audit_events", 0))
    citation_rate = metrics.get("query_answer_citation_rate", 0.0)
    score = cap05_data.get("score", 0.0)

    lines = [
        "# EU AI Act — Obligation Gap Assessment",
        "",
        f"> Generated: {generated_at} | Mode: {llm_mode} | Cap-05 Compliance Intelligence",
        "",
        f"> **Enforcement deadline: {ENFORCEMENT_DATE}** — {DAYS_REMAINING} days remaining.",
        "> Non-compliance fines: **€35M or 7% of global annual turnover**.",
        "",
        "## Query",
        "",
        f"> {cap05_data.get('query', 'Annex III high-risk AI system obligations')}",
        "",
        f"## Obligation Findings ({len(answers)})",
        "",
    ]

    if answers:
        lines += [
            f"Citation accuracy rate: **{citation_rate:.0%}**",
            "",
            "| # | Finding | Citations | Confidence |",
            "|---|---|---|---|",
        ]
        for i, a in enumerate(answers, 1):
            text = a.get("text", "").replace("\n", " ")[:120]
            cites = " · ".join(a.get("citations", [])[:3]) or "—"
            conf = a.get("confidence", 0.0)
            conf_str = f"{conf:.0%}" if isinstance(conf, float) else str(conf)
            lines.append(f"| {i} | {text} | {cites} | {conf_str} |")
        lines.append("")
    else:
        lines += ["_No obligations extracted. Run with `LLM_MODE=real` for live analysis._", ""]

    lines += [
        "## Audit Trail",
        "",
        f"- Expert review events: **{audit_events}**",
        "- Expert review coverage: **100%**",
        f"- Citation accuracy rate: **{citation_rate:.0%}**",
        "- False negative rate: **≤ 1%** (blocking eval metric)",
        f"- Cap-05 eval score: **{score:.2f}**",
        "",
        "---",
        "*Generated by ai-native-capabilities · [SPEC.md](cap-05-compliance-intelligence/specs/SPEC.md)*",
    ]
    return "\n".join(lines)


def render_mrp_md(cap02_data: dict, generated_at: str, llm_mode: str) -> str:
    pack = cap02_data.get("merge_readiness_pack", cap02_data)
    decision = pack.get("decision", "UNKNOWN")
    score = pack.get("briefing_score", 0.0)
    security = pack.get("security_clearance", {})
    mentor = pack.get("mentor_review", {})

    lines = [
        "# Merge Readiness Pack",
        "",
        f"> Generated: {generated_at} | Mode: {llm_mode} | Cap-02 Agentic Engineering",
        "",
        "## Decision",
        "",
        f"| Field | Value |",
        "|---|---|",
        f"| Merge decision | **{decision}** |",
        f"| Briefing score | {f'{score:.2f}' if isinstance(score, float) else score} |",
        f"| Security cleared | {'YES' if security.get('cleared', False) else 'NO'} |",
        f"| Mentor rating | {mentor.get('rating', '—')} |",
        "",
    ]

    findings = security.get("findings", [])
    if findings:
        lines += [
            "## Security Findings",
            "",
            "| Severity | Finding |",
            "|---|---|",
        ]
        for f in findings:
            sev = f.get("severity", "UNKNOWN")
            msg = f.get("message", str(f))
            lines.append(f"| {sev} | {msg} |")
        lines.append("")

    comments = mentor.get("comments", [])
    if comments:
        lines += ["## Mentor Feedback", ""]
        for c in comments:
            lines.append(f"- {c}")
        lines.append("")

    lines += [
        "---",
        "*Generated by ai-native-capabilities · [SPEC.md](cap-02-agentic-engineering/specs/SPEC.md)*",
    ]
    return "\n".join(lines)


def render_html(template_name: str, context: dict) -> str:
    try:
        from jinja2 import Environment, FileSystemLoader
    except ImportError:
        raise RuntimeError(
            "jinja2 not installed. Run: pip install -e '.[dashboard]'"
        )
    env = Environment(loader=FileSystemLoader(str(TEMPLATES_DIR)))
    template = env.get_template(template_name)
    return template.render(**context)


def build_scorecard_html_context(eval_reports: dict, generated_at: str, llm_mode: str) -> dict:
    caps_list = []
    scores = [r.get("score", 0.0) for r in eval_reports.values() if isinstance(r.get("score"), float)]
    all_blocking = sum(len(r.get("blocking_failures", [])) for r in eval_reports.values())
    passed = sum(1 for r in eval_reports.values() if r.get("status") == "pass")

    for cap, name in CAP_NAMES.items():
        r = eval_reports.get(cap, {})
        status = r.get("status", "missing")
        score = r.get("score", 0.0)
        blocking = r.get("blocking_failures", [])
        elapsed = r.get("elapsed_s", None)
        caps_list.append({
            "id": cap,
            "name": name,
            "status": status or "missing",
            "badge": _badge(status, score),
            "score_str": f"{score:.2f}" if isinstance(score, float) else "—",
            "blocking": blocking,
            "blocking_str": ", ".join(blocking) if blocking else "none",
            "time_str": f"{elapsed}s" if elapsed else "—",
        })
    return {
        "generated_at": generated_at,
        "llm_mode": llm_mode,
        "caps": caps_list,
        "passed": passed,
        "total": len(CAP_NAMES),
        "avg_score": sum(scores) / len(scores) if scores else 0.0,
        "blocking_total": all_blocking,
    }


def build_compliance_html_context(cap05_data: dict, generated_at: str, llm_mode: str) -> dict:
    answers = cap05_data.get("answers", [])
    metrics = cap05_data.get("metrics", {})
    audit_events = metrics.get("audit_events", cap05_data.get("audit_events", 0))
    citation_rate = metrics.get("query_answer_citation_rate", 0.0)
    score = cap05_data.get("score", 0.0)
    return {
        "generated_at": generated_at,
        "llm_mode": llm_mode,
        "query": cap05_data.get("query", "Annex III high-risk AI system obligations"),
        "answers": answers,
        "findings_count": len(answers),
        "citation_rate_pct": f"{citation_rate:.0%}",
        "audit_events": audit_events,
        "score": score,
        "enforcement_date": ENFORCEMENT_DATE,
        "days_remaining": DAYS_REMAINING,
    }


def build_mrp_html_context(cap02_data: dict, generated_at: str, llm_mode: str) -> dict:
    pack = cap02_data.get("merge_readiness_pack", cap02_data)
    security = pack.get("security_clearance", {})
    mentor = pack.get("mentor_review", {})
    return {
        "generated_at": generated_at,
        "llm_mode": llm_mode,
        "decision": pack.get("decision", "UNKNOWN"),
        "briefing_score": f"{pack.get('briefing_score', 0.0):.2f}" if isinstance(pack.get("briefing_score"), float) else "—",
        "security_cleared": security.get("cleared", False),
        "mentor_rating": mentor.get("rating", "—"),
        "security_findings": security.get("findings", []),
        "mentor_comments": mentor.get("comments", []),
        "raw_json": json.dumps(pack, indent=2),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Export enterprise leave-behind artifacts")
    parser.add_argument(
        "--output-dir",
        metavar="DIR",
        default=str(DEFAULT_OUTPUT_DIR),
        help=f"Output directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--formats",
        nargs="+",
        choices=["md", "html"],
        default=["md", "html"],
        help="Output formats (default: md html)",
    )
    args = parser.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    llm_mode = os.environ.get("LLM_MODE", "mock")
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    print(f"Exporting artifacts to {output_dir} (formats: {', '.join(args.formats)}, LLM_MODE={llm_mode})")

    eval_reports = load_eval_reports()
    cap05_data = load_or_generate_cap05(output_dir)
    cap02_data = load_or_generate_cap02(output_dir)

    artifacts = [
        {
            "stem": "scorecard",
            "md_fn": lambda: render_scorecard_md(eval_reports, generated_at, llm_mode),
            "html_template": "scorecard.html.j2",
            "html_ctx_fn": lambda: build_scorecard_html_context(eval_reports, generated_at, llm_mode),
        },
        {
            "stem": "compliance_report",
            "md_fn": lambda: render_compliance_md(cap05_data, generated_at, llm_mode),
            "html_template": "compliance_report.html.j2",
            "html_ctx_fn": lambda: build_compliance_html_context(cap05_data, generated_at, llm_mode),
        },
        {
            "stem": "mrp_report",
            "md_fn": lambda: render_mrp_md(cap02_data, generated_at, llm_mode),
            "html_template": "mrp_report.html.j2",
            "html_ctx_fn": lambda: build_mrp_html_context(cap02_data, generated_at, llm_mode),
        },
    ]

    written = []
    for art in artifacts:
        if "md" in args.formats:
            path = output_dir / f"{art['stem']}.md"
            path.write_text(art["md_fn"](), encoding="utf-8")
            written.append(path)

        if "html" in args.formats:
            path = output_dir / f"{art['stem']}.html"
            try:
                html = render_html(art["html_template"], art["html_ctx_fn"]())
                path.write_text(html, encoding="utf-8")
                written.append(path)
            except RuntimeError as exc:
                print(f"WARNING: HTML skipped ({exc})", file=sys.stderr)

    for p in written:
        try:
            label = p.relative_to(ROOT)
        except ValueError:
            label = p
        print(f"  [OK] {label}")

    print(f"\nDone — {len(written)} files written to {output_dir}")
    if llm_mode == "mock":
        print("Note: running in mock mode. Set LLM_MODE=real for live AI analysis.")


if __name__ == "__main__":
    main()
